<%
# To keep the YAML as simple as possible, some values are computed here
AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID'] ||'(ENTER_ACCESS_KEY_ID)'
AWS_ACCESS_KEY_SECRET = ENV['AWS_SECRET_KEY'] || '(ENTER_AWS_SECRET_ID)'
AWS_SSH_KEY_ID = ENV['AWS_SSH_KEY_ID'] || 'default'
AWS_SSH_KEYPATH = File.expand_path(ENV['AWS_SSH_KEY_PATH'] || "#{ENV['HOME']}/.ssh/id_rsa")
%>
---
driver:
  name: ec2
  aws_access_key_id: <%= AWS_ACCESS_KEY_ID %>
  aws_secret_access_key: <%= AWS_ACCESS_KEY_SECRET %>
  aws_ssh_key_id: <%= AWS_SSH_KEY_ID %>
  ssh_key: <%= AWS_SSH_KEYPATH %>
  region: us-east-1
  availability_zone: us-east-1c
  flavor_id: <%= ENV['AWS_FLAVOR_ID'] || '(ENTER_AWS_FLAVOR_ID)' %>
  require_chef_omnibus: true
  tags:
    created-by: 'test-kitchen'
    launched-by: <%= ENV['USER'] || '(ENTER_USER)' %>
    Name: 'test-kitchen-mesos-cookbook-<%= Time.now.to_i %>'

busser:
  sudo: true

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  data_path: test/shared

platforms:
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
  driver_config:
    image_id: ami-64e27e0c
    username: ubuntu

- name: ubuntu-12.04
  run_list:
    - recipe[apt]
  driver_config:
    image_id: ami-ccaed0a4
    username: ubuntu

- name: centos-6.4
  run_list:
    - recipe[yum::default]
  driver_config:
    image_id: ami-56009e3f
    username: ec2-user

- name: amazon-linux-2014-09-1
  run_list:
    - recipe[yum::default]
  driver_config:
    image_id: ami-246ed34c
    username: ec2-user

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[yum]
  - recipe[mesos::master]
  - recipe[mesos::slave]
