driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    - - forwarded_port
      - guest: 5050
        host: 5050
        auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  data_path: test/shared
  data_bags_path: test/integration/default/data_bags

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    - recipe[zookeeper-apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
    - recipe[zookeeper-apt]
  - name: debian-wheezy
    run_list:
    - recipe[apt]
    - recipe[zookeeper-apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]
    - recipe[zookeeper-yum]

suites:
- name: default
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]

- name: oraclejdk7
  run_list:
    - recipe[java]
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    java:
      jdk_version: '7'
      install_flavor: 'oracle'
      oracle:
        accept_oracle_download_terms: true
