driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    # Allow access to the Jenkins webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 5050
        host: 5050
        auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.10.0
  data_path: test/shared

platforms:
- name: ubuntu-12.04
  run_list:
    - recipe[apt]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

- name: ubuntu-13.04
  run_list:
    - recipe[apt]
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box

- name: centos-6.5
  run_list:
    - recipe[yum]
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

suites:
- name: default
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]

- name: oraclejdk7
  run_list:
    - recipe[java]
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    java:
      jdk_version: '7'
      install_flavor: 'oracle'
      oracle:
        accept_oracle_download_terms: true
