<%
# To keep the YAML as simple as possible, some values are computed here
AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID'] ||'(ENTER_ACCESS_KEY_ID)'
AWS_ACCESS_KEY_SECRET = ENV['AWS_SECRET_KEY'] || '(ENTER_AWS_SECRET_ID)'
AWS_FLAVOR_ID = ENV['AWS_FLAVOR_ID'] || '(ENTER_AWS_FLAVOR_ID)'
AWS_SSH_KEY_ID = ENV['AWS_SSH_KEY_ID'] || 'default'
AWS_SSH_KEYPATH = File.expand_path(ENV['AWS_SSH_KEY_PATH'] || "#{ENV['HOME']}/.ssh/id_rsa")
USER = ENV['USER'] || '(ENTER_USER)'
%>
---
driver:
  name: ec2
  aws_access_key_id: <%= AWS_ACCESS_KEY_ID %>
  aws_secret_access_key: <%= AWS_ACCESS_KEY_SECRET %>
  aws_ssh_key_id: <%= AWS_SSH_KEY_ID %>
  ssh_key: <%= AWS_SSH_KEYPATH %>
  region: us-east-1
  availability_zone: us-east-1c
  flavor_id: <%= AWS_FLAVOR_ID %>
  require_chef_omnibus: true
  tags:
    created-by: 'test-kitchen'
    launched-by: <%= USER %>
    Name: 'test-kitchen-mesos-cookbook-<%= Time.now.to_i %>'

busser:
  sudo: true

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  data_path: test/shared

platforms:
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
    - recipe[zookeeper-apt]
  driver_config:
    image_id: ami-64e27e0c
    username: ubuntu

- name: ubuntu-12.04
  run_list:
    - recipe[apt]
    - recipe[zookeeper-apt]
  driver_config:
    image_id: ami-ccaed0a4
    username: ubuntu

- name: debian-wheezy
  run_list:
    - recipe[apt]
    - recipe[zookeeper-apt]
  driver_config:
    image_id: ami-2c886c44
    username: admin

- name: centos-6.4
  run_list:
    - recipe[yum::default]
    - recipe[zookeeper-yum]
  driver_config:
    image_id: ami-52009e3b
    username: ec2-user

suites:
- name: default
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]

- name: oraclejdk7
  run_list:
    - recipe[java]
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    java:
      jdk_version: '7'
      install_flavor: 'oracle'
      oracle:
        accept_oracle_download_terms: true
