---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1024
    network:
    - ["forwarded_port", {guest: 5050, host: 5050}]

- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
    customize:
      memory: 1024
    network:
    - ["forwarded_port", {guest: 5050, host: 5050}]

- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
    customize:
      memory: 1024
    network:
    - ["forwarded_port", {guest: 5050, host: 5050}]

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[mesosphere_mesos::master]
  - recipe[mesosphere_mesos::slave]
  - recipe[minitest-handler]
  attributes:
    mesos:
      version: '0.15.0'
      enable_master: false
      enable_slave: false
      #zookeeper_server_list: []
      #zookeeper_port: 2181
      #zookeeper_path: 'mesos-test'
