---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1024
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    customize:
      memory: 1024

suites:
- name: default
  run_list:
  - recipe[mesos]
  - recipe[apt]
  attributes:
    mesos:
      version: '0.15.0-trunk-d20130921'
      master: false
      slave: true
      #zookeeper_server_list: [ 'ec2-54-211-195-173.compute-1.amazonaws.com', 'ec2-54-242-24-191.compute-1.amazonaws.com', 'ec2-50-16-61-190.compute-1.amazonaws.com' ]
      zookeeper_port: 2181
      zookeeper_path: 'mesos-test'
      zookeeper_exhibitor_discovery: false
      zookeeper_exhibitor_url: 'http://zk-sandbox.imedidata.net:8080'
